"""
Dependency-free structure I/O: extended-XYZ (MACE/CP-MACE format) and
LAMMPS data file writers, operating directly on plain arrays so they work
even without ase/pymatgen installed.
"""

import numpy as np


def write_extxyz(path, species, positions, cell, forces=None, energy=None,
                  extra_fields=None):
    """Write a single-frame extended-XYZ file.

    `cell` is a 3x3 array of lattice row-vectors. `extra_fields` is a dict
    of scalar fields appended to the comment line -- for CP-MACE datasets,
    pass e.g. {"electron": 661.7, "potential": -3.407347}.
    """
    n = len(species)
    positions = np.asarray(positions, dtype=float)
    lat = " ".join(f"{v:.6f}" for v in np.asarray(cell, dtype=float).flatten())
    props = "species:S:1:pos:R:3"
    if forces is not None:
        props += ":REF_forces:R:3"
        forces = np.asarray(forces, dtype=float)
    header = f'Lattice="{lat}" Properties={props} pbc="T T T"'
    if energy is not None:
        header += f" REF_energy={energy:.8f}"
    if extra_fields:
        for key, value in extra_fields.items():
            header += f" {key}={value}"
    lines = [str(n), header]
    for i in range(n):
        row = f"{species[i]:<3s} {positions[i, 0]:.8f} {positions[i, 1]:.8f} {positions[i, 2]:.8f}"
        if forces is not None:
            row += f" {forces[i, 0]:.8f} {forces[i, 1]:.8f} {forces[i, 2]:.8f}"
        lines.append(row)
    text = "\n".join(lines) + "\n"
    with open(path, "w") as fh:
        fh.write(text)
    return text


def write_lammps_data(path, species, positions, cell, masses, charges=None,
                       atom_style="full"):
    """Write a minimal orthogonal-cell LAMMPS data file.

    `masses` is a dict {species_symbol: mass_amu}. Species are mapped to
    LAMMPS type IDs in sorted order for reproducibility across runs.
    Returns (text, type_map) where type_map is {species: lammps_type_id}.
    """
    positions = np.asarray(positions, dtype=float)
    unique_species = sorted(set(species))
    type_map = {s: i + 1 for i, s in enumerate(unique_species)}
    n = len(species)
    lx, ly, lz = np.diag(np.asarray(cell, dtype=float))
    lines = [
        "# LAMMPS data file generated by electrochem-agents systems.io_utils",
        "",
        f"{n} atoms",
        f"{len(unique_species)} atom types",
        "",
        f"0.0 {lx:.6f} xlo xhi",
        f"0.0 {ly:.6f} ylo yhi",
        f"0.0 {lz:.6f} zlo zhi",
        "",
        "Masses",
        "",
    ]
    for s in unique_species:
        lines.append(f"{type_map[s]} {masses[s]:.4f}  # {s}")
    lines += ["", f"Atoms  # {atom_style}", ""]
    for i in range(n):
        q = charges[i] if charges is not None else 0.0
        tid = type_map[species[i]]
        if atom_style == "full":
            lines.append(
                f"{i + 1} 1 {tid} {q:.4f} "
                f"{positions[i, 0]:.6f} {positions[i, 1]:.6f} {positions[i, 2]:.6f}"
            )
        else:
            lines.append(
                f"{i + 1} {tid} "
                f"{positions[i, 0]:.6f} {positions[i, 1]:.6f} {positions[i, 2]:.6f}"
            )
    text = "\n".join(lines) + "\n"
    with open(path, "w") as fh:
        fh.write(text)
    return text, type_map
